[package]
name = "eva-macos"
version.workspace = true
edition.workspace = true
license.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSString", "NSURL", "NSArray", "NSGeometry", "NSRunLoop", "NSDate", "NSData", "NSDictionary"] }
objc2-app-kit = { version = "0.3", features = [
    "NSApplication",
    "NSPanel",
    "NSWindow",
    "NSView",
    "NSResponder",
    "NSTextField",
    "NSPasteboard",
    "NSPasteboardItem",
    "NSWorkspace",
    "NSRunningApplication",
    "NSScreen",
    "NSColor",
    "NSFont",
    "NSResponder",
    "NSEvent",
    "NSControl",
    "NSText",
    "NSParagraphStyle",
    "NSBitmapImageRep",
    "NSImage",
    "NSImageView",
    "NSImageRep",
    "block2",
] }
block2 = "0.6"
notify-rust = "4"
objc2-core-graphics = "0.3"
thiserror = { workspace = true }
tracing = { workspace = true }
objc2-application-services = "0.3.2"
objc2-core-foundation = "0.3.2"
dirs = "5"
objc2-quartz-core = { version = "0.3", features = [
    "CALayer",
    "CATransaction",
    "CAMediaTimingFunction",
    "objc2-core-foundation",
    "block2",
] }

[dependencies]
serde = { workspace = true }

[dev-dependencies]
tempfile = "3"
